const express = require('express');
const router = express.Router();
const Bot = require('../models/Bot');
const { requireAuth } = require('../middleware/auth');

// Get all bots for user
router.get('/', requireAuth, async (req, res) => {
  try {
    const bots = await Bot.find({ userId: req.session.userId })
      .select('-generatedCode -token')
      .sort({ updatedAt: -1 });
    res.json({ bots });
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch bots' });
  }
});

// Get single bot
router.get('/:id', requireAuth, async (req, res) => {
  try {
    const bot = await Bot.findOne({ _id: req.params.id, userId: req.session.userId });
    if (!bot) return res.status(404).json({ error: 'Bot not found' });
    // Mask token partially
    const b = bot.toObject();
    if (b.token) b.token = b.token.substring(0, 20) + '...' + b.token.slice(-5);
    res.json({ bot: b });
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch bot' });
  }
});

// Create bot
router.post('/', requireAuth, async (req, res) => {
  try {
    const data = req.body;
    if (!data.name) return res.status(400).json({ error: 'Bot name required' });
    if (!data.token) return res.status(400).json({ error: 'Bot token required' });

    const bot = await Bot.create({ ...data, userId: req.session.userId });
    const code = generateBotCode(bot);
    bot.generatedCode = code;
    await bot.save();

    res.json({ success: true, bot: { _id: bot._id, name: bot.name }, code });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to create bot' });
  }
});

// Update bot
router.put('/:id', requireAuth, async (req, res) => {
  try {
    const bot = await Bot.findOne({ _id: req.params.id, userId: req.session.userId });
    if (!bot) return res.status(404).json({ error: 'Bot not found' });

    Object.assign(bot, req.body);
    const code = generateBotCode(bot);
    bot.generatedCode = code;
    await bot.save();

    res.json({ success: true, code });
  } catch (err) {
    res.status(500).json({ error: 'Failed to update bot' });
  }
});

// Delete bot
router.delete('/:id', requireAuth, async (req, res) => {
  try {
    await Bot.findOneAndDelete({ _id: req.params.id, userId: req.session.userId });
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: 'Failed to delete bot' });
  }
});

// Get generated code
router.get('/:id/code', requireAuth, async (req, res) => {
  try {
    const bot = await Bot.findOne({ _id: req.params.id, userId: req.session.userId });
    if (!bot) return res.status(404).json({ error: 'Bot not found' });
    const code = generateBotCode(bot);
    res.json({ code });
  } catch (err) {
    res.status(500).json({ error: 'Failed to generate code' });
  }
});

// ─────────────────────────────────────────────
//  CODE GENERATOR
// ─────────────────────────────────────────────
function generateBotCode(bot) {
  const f = bot.features || {};
  const sc = bot.slashBuiltins || {};
  const mc = bot.modCommands || {};
  const le = bot.logEvents || {};
  const em = bot.embed || {};
  const ar = bot.autoRole || {};
  const colorHex = (em.color || '#5865F2').replace('#', '0x');
  const roleIds = (ar.roleIds || []).filter(Boolean);
  const customCmds = (bot.commands || []);

  let code = `# ============================================================
#   W3EKLY BOTS — Generated by W3eklyBots Creator BETA v1.0.0
#   Bot: ${bot.name}
#   Generated: ${new Date().toLocaleString()}
#   W3eklyStudios © ${new Date().getFullYear()}
# ============================================================
#
#   INSTALL:  pip install discord.py
#   RUN:      python bot.py
# ============================================================

import discord
from discord import app_commands, Embed
from discord.ext import commands
import asyncio
from datetime import datetime

# ─────────────────────────────────────────────
#  BOT TOKEN — Replace with your actual token
# ─────────────────────────────────────────────
BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"

# ─────────────────────────────────────────────
#  INTENTS & BOT SETUP
# ─────────────────────────────────────────────
intents = discord.Intents.default()
intents.members = True
intents.message_content = True
intents.guilds = True
intents.reactions = True

bot = commands.Bot(command_prefix="${bot.prefix || '!'}", intents=intents)
tree = bot.tree

BOT_VERSION = "1.0.0"
BOT_NAME    = "${bot.name}"


# ─────────────────────────────────────────────
#  EMBED HELPER  (W3eklyBots Style)
# ─────────────────────────────────────────────
def make_embed(
    title: str = "${em.title || 'Announcement'}",
    description: str = "${em.description || ''}",
    color: int = ${colorHex},
    author: str = "${em.author || bot.name}",
    footer: str = "${em.footer || 'W3eklyBots'}",
    image_url: str = None,
    thumbnail_url: str = None,
    fields: list = None,
    timestamp: bool = True,
) -> Embed:
    embed = Embed(
        title=title,
        description=description,
        color=color,
        timestamp=datetime.utcnow() if timestamp else None,
    )
    embed.set_author(name=author, icon_url=bot.user.display_avatar.url if bot.user else None)
    embed.set_footer(text=footer, icon_url=bot.user.display_avatar.url if bot.user else None)
    if image_url:
        embed.set_image(url=image_url)
    if thumbnail_url:
        embed.set_thumbnail(url=thumbnail_url)
    if fields:
        for f in fields:
            name, value, inline = (list(f) + [True])[:3]
            embed.add_field(name=name, value=value, inline=inline)
    return embed


# ─────────────────────────────────────────────
#  ON READY
# ─────────────────────────────────────────────
@bot.event
async def on_ready():
    print(f"\\n{'='*50}")
    print(f"  {BOT_NAME} is online!")
    print(f"  Logged in as: {bot.user} ({bot.user.id})")
    print(f"  Guilds: {len(bot.guilds)}")
    print(f"  W3eklyBots Creator BETA v1.0.0")
    print(f"  W3eklyStudios © ${new Date().getFullYear()}")
    print(f"{'='*50}\\n")
    try:
        synced = await tree.sync()
        print(f"[/] Synced {len(synced)} slash command(s)")
    except Exception as e:
        print(f"[/] Sync failed: {e}")

    activity_map = {
        "playing":   discord.Activity(type=discord.ActivityType.playing,   name="${bot.statusMessage || 'Powered by W3eklyBots'}"),
        "watching":  discord.Activity(type=discord.ActivityType.watching,  name="${bot.statusMessage || 'Powered by W3eklyBots'}"),
        "listening": discord.Activity(type=discord.ActivityType.listening, name="${bot.statusMessage || 'Powered by W3eklyBots'}"),
        "competing": discord.Activity(type=discord.ActivityType.competing, name="${bot.statusMessage || 'Powered by W3eklyBots'}"),
    }
    activity = activity_map.get("${bot.statusType || 'playing'}", activity_map["playing"])
    await bot.change_presence(status=discord.Status.online, activity=activity)
`;

  // ── SLASH COMMANDS ──
  if (f.slashCommands) {
    code += `\n\n# ─────────────────────────────────────────────\n#  SLASH COMMANDS\n# ─────────────────────────────────────────────\n`;

    if (sc.ping) code += `
@tree.command(name="ping", description="Check the bot latency")
async def slash_ping(interaction: discord.Interaction):
    latency = round(bot.latency * 1000)
    embed = make_embed(title="🏓 Pong!", description=f"Latency: **{latency}ms**", color=0x57F287,
        fields=[("API Latency", f"{latency}ms", True), ("Status", "🟢 Online", True)])
    await interaction.response.send_message(embed=embed)
`;
    if (sc.help) code += `
@tree.command(name="help", description="Show all available commands")
async def slash_help(interaction: discord.Interaction):
    embed = make_embed(title="📖 Help — ${bot.name}",
        description="Here are all available commands:",
        fields=[
            ("⚡ Slash", "\`/ping\` \`/help\`", False),
            ("📌 Prefix", f"Use \`${bot.prefix || '!'}\` before commands", False),
        ])
    await interaction.response.send_message(embed=embed, ephemeral=True)
`;
    if (sc.serverinfo) code += `
@tree.command(name="serverinfo", description="Server information")
async def slash_serverinfo(interaction: discord.Interaction):
    g = interaction.guild
    embed = make_embed(title=f"🏠 {g.name}", description=g.description or "No description.",
        fields=[("👑 Owner", g.owner.mention, True), ("👥 Members", str(g.member_count), True),
                ("📅 Created", g.created_at.strftime("%Y-%m-%d"), True),
                ("🎭 Roles", str(len(g.roles)), True), ("📺 Channels", str(len(g.channels)), True)])
    if g.icon: embed.set_thumbnail(url=g.icon.url)
    await interaction.response.send_message(embed=embed)
`;
    if (sc.userinfo) code += `
@tree.command(name="userinfo", description="Get info about a user")
@app_commands.describe(member="Target member")
async def slash_userinfo(interaction: discord.Interaction, member: discord.Member = None):
    m = member or interaction.user
    roles = [r.mention for r in m.roles if r.name != "@everyone"]
    embed = make_embed(title=f"👤 {m.display_name}",
        description=f"**{m}** ({m.id})",
        fields=[("Joined", m.joined_at.strftime("%Y-%m-%d") if m.joined_at else "N/A", True),
                ("Created", m.created_at.strftime("%Y-%m-%d"), True),
                ("Top Role", m.top_role.mention, True),
                ("Roles", " ".join(roles) or "None", False)],
        thumbnail_url=m.display_avatar.url)
    await interaction.response.send_message(embed=embed)
`;
    if (sc.avatar) code += `
@tree.command(name="avatar", description="Get a user's avatar")
@app_commands.describe(member="Target member")
async def slash_avatar(interaction: discord.Interaction, member: discord.Member = None):
    m = member or interaction.user
    embed = make_embed(title=f"🖼️ {m.display_name}'s Avatar",
        description=f"[Open in browser]({m.display_avatar.url})",
        image_url=m.display_avatar.url, color=0xEB459E)
    await interaction.response.send_message(embed=embed)
`;
    if (sc.say) code += `
@tree.command(name="say", description="Make the bot send a message")
@app_commands.describe(message="Message text", channel="Target channel")
@app_commands.default_permissions(administrator=True)
async def slash_say(interaction: discord.Interaction, message: str, channel: discord.TextChannel = None):
    target = channel or interaction.channel
    await target.send(message)
    await interaction.response.send_message(f"✅ Sent to {target.mention}", ephemeral=True)
`;

    if (f.embedBuilder) code += `
@tree.command(name="embed", description="Send a styled embed")
@app_commands.describe(title="Embed title", description="Embed body", color="Hex color e.g. #5865F2", channel="Target channel")
@app_commands.default_permissions(manage_messages=True)
async def slash_embed(interaction: discord.Interaction, title: str, description: str, color: str = "${em.color || '#5865F2'}", channel: discord.TextChannel = None):
    target = channel or interaction.channel
    try: col = int(color.lstrip("#"), 16)
    except: col = ${colorHex}
    embed = make_embed(title=title, description=description, color=col)
    await target.send(embed=embed)
    await interaction.response.send_message("✅ Embed sent!", ephemeral=True)
`;

    // Custom commands
    customCmds.filter(c => c.type === 'slash').forEach(cmd => {
      const fnName = (cmd.name || 'custom').replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
      if (cmd.embedResponse) {
        code += `
@tree.command(name="${cmd.name}", description="${cmd.description || 'Custom command'}")
async def slash_${fnName}(interaction: discord.Interaction):
    embed = make_embed(title="${cmd.embedTitle || cmd.name}", description="${cmd.response || ''}", color=${(cmd.embedColor || '#5865F2').replace('#', '0x')})
    await interaction.response.send_message(embed=embed${cmd.ephemeral ? ', ephemeral=True' : ''})
`;
      } else {
        code += `
@tree.command(name="${cmd.name}", description="${cmd.description || 'Custom command'}")
async def slash_${fnName}(interaction: discord.Interaction):
    await interaction.response.send_message("${cmd.response || 'Hello!'}"${cmd.ephemeral ? ', ephemeral=True' : ''})
`;
      }
    });
  }

  // ── PREFIX COMMANDS ──
  if (f.prefixCommands) {
    code += `\n\n# ─────────────────────────────────────────────\n#  PREFIX COMMANDS  (prefix: "${bot.prefix || '!'}")\n# ─────────────────────────────────────────────\n`;
    code += `
@bot.command(name="ping")
async def prefix_ping(ctx):
    embed = make_embed(title="🏓 Pong!", description=f"Latency: **{round(bot.latency*1000)}ms**", color=0x57F287)
    await ctx.send(embed=embed)

@bot.command(name="help")
async def prefix_help(ctx):
    embed = make_embed(title="📖 Help", description=f"Prefix: \`${bot.prefix || '!'}\`")
    await ctx.send(embed=embed)
`;
    customCmds.filter(c => c.type === 'prefix').forEach(cmd => {
      const fnName = (cmd.name || 'custom').replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
      if (cmd.embedResponse) {
        code += `
@bot.command(name="${cmd.name}")
async def prefix_${fnName}(ctx):
    embed = make_embed(title="${cmd.embedTitle || cmd.name}", description="${cmd.response || ''}", color=${(cmd.embedColor || '#5865F2').replace('#', '0x')})
    await ctx.send(embed=embed)
`;
      } else {
        code += `
@bot.command(name="${cmd.name}")
async def prefix_${fnName}(ctx):
    await ctx.send("${cmd.response || 'Hello!'}")
`;
      }
    });
  }

  // ── MODERATION ──
  if (f.moderation) {
    code += `\n\n# ─────────────────────────────────────────────\n#  MODERATION COMMANDS\n# ─────────────────────────────────────────────\n`;
    if (mc.kick) code += `
@bot.command(name="kick")
@commands.has_permissions(kick_members=True)
async def mod_kick(ctx, member: discord.Member, *, reason="No reason"):
    await member.kick(reason=reason)
    await ctx.send(embed=make_embed(title="👢 Kicked", description=f"{member.mention} was kicked\\n**Reason:** {reason}", color=0xFEE75C))
`;
    if (mc.ban) code += `
@bot.command(name="ban")
@commands.has_permissions(ban_members=True)
async def mod_ban(ctx, member: discord.Member, *, reason="No reason"):
    await member.ban(reason=reason)
    await ctx.send(embed=make_embed(title="🔨 Banned", description=f"{member.mention} was banned\\n**Reason:** {reason}", color=0xED4245))
`;
    if (mc.mute) code += `
@bot.command(name="mute")
@commands.has_permissions(manage_roles=True)
async def mod_mute(ctx, member: discord.Member, *, reason="No reason"):
    mute_role = discord.utils.get(ctx.guild.roles, name="Muted")
    if not mute_role:
        mute_role = await ctx.guild.create_role(name="Muted")
        for ch in ctx.guild.channels:
            await ch.set_permissions(mute_role, speak=False, send_messages=False)
    await member.add_roles(mute_role, reason=reason)
    await ctx.send(embed=make_embed(title="🔇 Muted", description=f"{member.mention} muted\\n**Reason:** {reason}", color=0xFEE75C))
`;
    if (mc.clear) code += `
@bot.command(name="clear", aliases=["purge"])
@commands.has_permissions(manage_messages=True)
async def mod_clear(ctx, amount: int = 10):
    await ctx.channel.purge(limit=amount + 1)
    m = await ctx.send(embed=make_embed(title="🧹 Cleared", description=f"Deleted **{amount}** messages.", color=0x57F287))
    await asyncio.sleep(3)
    await m.delete()
`;
    if (mc.warn) code += `
warn_db = {}
@bot.command(name="warn")
@commands.has_permissions(manage_messages=True)
async def mod_warn(ctx, member: discord.Member, *, reason="No reason"):
    uid = str(member.id)
    warn_db[uid] = warn_db.get(uid, []) + [reason]
    await ctx.send(embed=make_embed(title="⚠️ Warned", description=f"{member.mention} warned\\n**Reason:** {reason}\\n**Total:** {len(warn_db[uid])}", color=0xFEE75C))
`;
    if (mc.unban) code += `
@bot.command(name="unban")
@commands.has_permissions(ban_members=True)
async def mod_unban(ctx, *, username: str):
    async for e in ctx.guild.bans():
        if str(e.user) == username:
            await ctx.guild.unban(e.user)
            return await ctx.send(embed=make_embed(title="✅ Unbanned", description=f"**{username}** unbanned.", color=0x57F287))
    await ctx.send(embed=make_embed(title="❌ Not Found", description=f"No ban for **{username}**.", color=0xED4245))
`;
  }

  // ── AUTO ROLE + WELCOME ──
  if (f.autoRole || f.welcomeMessage) {
    const roleIdList = roleIds.length ? roleIds.map(r => `"${r}"`).join(', ') : '';
    const wCh = ar.welcomeChannelId || '';
    const wMsg = (ar.welcomeMessage || 'Welcome {member.mention}!').replace(/"/g, '\\"');
    code += `\n\n# ─────────────────────────────────────────────\n#  AUTO ROLE + WELCOME\n# ─────────────────────────────────────────────\n`;
    code += `
# Role IDs to assign on join
AUTO_ROLE_IDS = [${roleIdList}]
WELCOME_CHANNEL_ID = ${wCh ? `"${wCh}"` : 'None'}  # Set your channel ID here

@bot.event
async def on_member_join(member: discord.Member):
    guild = member.guild

    # Assign roles by ID
    for role_id in AUTO_ROLE_IDS:
        role = guild.get_role(int(role_id))
        if role:
            try:
                await member.add_roles(role)
            except discord.Forbidden:
                print(f"[AUTO ROLE] Cannot assign role ID {role_id}")
        else:
            print(f"[AUTO ROLE] Role ID {role_id} not found")
`;
    if (f.welcomeMessage && wCh) code += `
    # Send welcome message
    welcome_ch = guild.get_channel(int(WELCOME_CHANNEL_ID)) if WELCOME_CHANNEL_ID else None
    if welcome_ch:
        role_name = guild.get_role(int(AUTO_ROLE_IDS[0])).name if AUTO_ROLE_IDS else "Member"
        embed = make_embed(
            title="👋 Welcome!",
            description="${wMsg}".replace("{member.mention}", member.mention).replace("{role}", role_name),
            color=0x57F287,
            thumbnail_url=member.display_avatar.url,
            fields=[("📅 Account Created", member.created_at.strftime("%Y-%m-%d"), True),
                    ("👥 Member #", str(guild.member_count), True)]
        )
        await welcome_ch.send(embed=embed)
`;
    if (f.dmOnJoin) code += `
    # DM the new member
    try:
        await member.send(embed=make_embed(
            title=f"Welcome to {guild.name}! 🎉",
            description=f"Thanks for joining **{guild.name}**! Use \`/help\` to get started.",
            color=0x5865F2
        ))
    except discord.Forbidden:
        pass
`;
  }

  // ── LOGGING ──
  if (f.logging) {
    const lCh = ar.logChannelId || '';
    code += `\n\n# ─────────────────────────────────────────────\n#  EVENT LOGGING\n# ─────────────────────────────────────────────\n`;
    code += `LOG_CHANNEL_ID = ${lCh ? `"${lCh}"` : 'None'}  # Set your log channel ID\n`;
    code += `
async def get_log_ch(guild):
    if LOG_CHANNEL_ID:
        return guild.get_channel(int(LOG_CHANNEL_ID))
    return None
`;
    if (le.memberJoin) code += `
@bot.event
async def on_member_join(member: discord.Member):  # noqa
    ch = await get_log_ch(member.guild)
    if ch:
        await ch.send(embed=make_embed(title="📥 Joined", description=member.mention, color=0x57F287,
            fields=[("ID", str(member.id), True), ("Created", member.created_at.strftime("%Y-%m-%d"), True)],
            thumbnail_url=member.display_avatar.url))
`;
    if (le.memberLeave) code += `
@bot.event
async def on_member_remove(member: discord.Member):
    ch = await get_log_ch(member.guild)
    if ch:
        await ch.send(embed=make_embed(title="📤 Left", description=str(member), color=0xED4245,
            fields=[("ID", str(member.id), True)]))
`;
    if (le.messageDelete) code += `
@bot.event
async def on_message_delete(message: discord.Message):
    if message.author.bot or not message.guild: return
    ch = await get_log_ch(message.guild)
    if ch:
        await ch.send(embed=make_embed(title="🗑️ Message Deleted", description=f"In {message.channel.mention}",
            color=0xFEE75C, fields=[("Author", message.author.mention, True), ("Content", message.content[:1024] or "*empty*", False)]))
`;
    if (le.messageEdit) code += `
@bot.event
async def on_message_edit(before: discord.Message, after: discord.Message):
    if before.author.bot or not before.guild or before.content == after.content: return
    ch = await get_log_ch(before.guild)
    if ch:
        await ch.send(embed=make_embed(title="✏️ Message Edited", description=f"By {before.author.mention} in {before.channel.mention}",
            color=0x5865F2, fields=[("Before", before.content[:512] or "*empty*", False), ("After", after.content[:512] or "*empty*", False)]))
`;
  }

  // ── REACTION ROLES ──
  if (f.reactionRoles) code += `\n\n# ─────────────────────────────────────────────\n#  REACTION ROLES\n# ─────────────────────────────────────────────\n# Format: { message_id: { "emoji": role_id } }\nREACTION_ROLES = {\n    # 1234567890123456789: { "⭐": 9876543210987654321 }\n}\n\n@bot.event\nasync def on_raw_reaction_add(payload):\n    if payload.message_id not in REACTION_ROLES: return\n    guild = bot.get_guild(payload.guild_id)\n    emoji = str(payload.emoji)\n    role_id = REACTION_ROLES[payload.message_id].get(emoji)\n    if not role_id: return\n    role = guild.get_role(int(role_id))\n    member = guild.get_member(payload.user_id)\n    if role and member: await member.add_roles(role)\n\n@bot.event\nasync def on_raw_reaction_remove(payload):\n    if payload.message_id not in REACTION_ROLES: return\n    guild = bot.get_guild(payload.guild_id)\n    emoji = str(payload.emoji)\n    role_id = REACTION_ROLES[payload.message_id].get(emoji)\n    if not role_id: return\n    role = guild.get_role(int(role_id))\n    member = guild.get_member(payload.user_id)\n    if role and member: await member.remove_roles(role)\n`;

  // ── ERROR HANDLER ──
  if (f.errorHandler) code += `\n\n# ─────────────────────────────────────────────\n#  ERROR HANDLER\n# ─────────────────────────────────────────────\n@bot.event\nasync def on_command_error(ctx, error):\n    if isinstance(error, commands.MissingPermissions):\n        em = make_embed(title="❌ No Permission", description="You lack permissions.", color=0xED4245)\n    elif isinstance(error, commands.MissingRequiredArgument):\n        em = make_embed(title="⚠️ Missing Argument", description=f"Usage: \`{ctx.prefix}{ctx.command.name} {ctx.command.signature}\`", color=0xFEE75C)\n    elif isinstance(error, commands.CommandNotFound):\n        return\n    else:\n        em = make_embed(title="💥 Error", description=f"\`\`\`{str(error)[:400]}\`\`\`", color=0xED4245)\n    await ctx.send(embed=em, delete_after=8)\n\n@tree.error\nasync def on_app_error(interaction, error):\n    msg = str(error)[:200]\n    em = make_embed(title="❌ Error", description=msg, color=0xED4245)\n    try: await interaction.response.send_message(embed=em, ephemeral=True)\n    except: await interaction.followup.send(embed=em, ephemeral=True)\n`;

  code += `\n\n# ─────────────────────────────────────────────\n#  RUN\n# ─────────────────────────────────────────────\nif __name__ == "__main__":\n    if BOT_TOKEN == "YOUR_BOT_TOKEN_HERE":\n        raise ValueError("Please set your BOT_TOKEN variable at the top of this file!")\n    bot.run(BOT_TOKEN)\n`;

  return code;
}

module.exports = router;
